### ISSUE TITLE
Inline and Crossline displays (3D)

### ISSUE THREAD

**Issue by EvanBianco** [agile-geoscience/seisplot#28]
Coupled inline and crossline display for 3D seismic. Need to integrate with annotation from #24

**Comment by EvanBianco** [comment]
Sort / reshape traces into 3D array: 

- Need to build a `np.meshgrid`like array for a 3D data volume holding the x_coordinate, y_coordinate, inline number, and crossline number for each trace.
- Add configuration parameters to YAML for choosing inlines and xlines to display (maybe choose "middles" if no parameters are specificied.
- Refactor Matplotlib Figure window to take two seismic axes.
- Link displays using annotation to each other (vertical lines for intersections), and (later) to basemap (issue #24)

**Comment by kwinkunks** [comment]
This is basically working. With caveats like #34
